# Generated by Django 5.2.3 on 2026-09-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Company / Business Name')),
                ('project_type', models.CharField(choices=[('Business Website', 'Business Website'), ('E-Commerce', 'E-Commerce Website'), ('Custom Web Application', 'Custom Web Application'), ('Booking System', 'Booking System'), ('Management System', 'Management System'), ('Portfolio', 'Portfolio Website'), ('Landing Page', 'Landing Page'), ('Custom Software Solutions', 'Custom Software Solutions'), ('Other', 'Other')], default='Custom Web Application', max_length=100, verbose_name='Project Type')),
                ('budget', models.CharField(blank=True, choices=[('Under ₹25,000', 'Under ₹25,000'), ('₹25,000 – ₹50,000', '₹25,000 – ₹50,000'), ('₹50,000 – ₹1,00,000', '₹50,000 – ₹1,00,000'), ('₹1,00,000+', '₹1,00,000+'), ('Not Sure', 'Not Sure / To Discuss')], default='Not Sure', max_length=100, null=True, verbose_name='Budget Range')),
                ('message', models.TextField(verbose_name='Project Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
                ('status', models.CharField(choices=[('New', 'New Lead'), ('Contacted', 'Contacted'), ('In Progress', 'In Progress / Discussion'), ('Completed', 'Completed / Converted')], default='New', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Project Enquiry',
                'verbose_name_plural': 'Project Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
