# Generated by Django 5.2.3 on 2026-09-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='budget',
            field=models.CharField(blank=True, choices=[('Not Sure', 'Not Sure / To Discuss'), ('Under ₹25,000', 'Under ₹25,000'), ('₹25,000 - ₹50,000', '₹25,000 - ₹50,000'), ('₹50,000 - ₹1,00,000', '₹50,000 - ₹1,00,000'), ('₹1,00,000+', '₹1,00,000+')], default='Not Sure', max_length=150, null=True, verbose_name='Budget Range'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='project_type',
            field=models.CharField(choices=[('Business Website', 'Business Website'), ('E-Commerce', 'E-Commerce Website'), ('Custom Web Application', 'Custom Web Application'), ('Booking System', 'Booking System'), ('Management System', 'Management System'), ('Portfolio', 'Portfolio Website'), ('Landing Page', 'Landing Page'), ('Custom Software Solutions', 'Custom Software Solutions'), ('Other', 'Other')], default='Custom Web Application', max_length=150, verbose_name='Project Type'),
        ),
    ]
