# Generated by Django 5.2.3 on 2026-09-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_alter_contactmessage_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='budget',
            field=models.CharField(blank=True, choices=[('Not Sure', 'Not Sure / To Discuss'), ('₹5,000 - ₹10,000', '₹5,000 - ₹10,000'), ('₹10,000 - ₹25,000', '₹10,000 - ₹25,000'), ('₹25,000 - ₹50,000', '₹25,000 - ₹50,000'), ('₹50,000 - ₹1,00,000', '₹50,000 - ₹1,00,000'), ('₹1,00,000+', '₹1,00,000+')], default='Not Sure', max_length=150, null=True, verbose_name='Budget Range'),
        ),
    ]
